server:
  port: 9999
  servlet:
    context-path:

spring:
  profiles:
    active: @spring.active@

mybatis-plus:
  mapper-locations: classpath*:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl